apiVersion: v1
kind: Pod
metadata:
  name: user4-pytorch-lenet-3
  namespace: user4
spec:
  schedulerName: my-scheduler
  restartPolicy: OnFailure
  containers:
  - name: pytorch-egpu-ctr
    image: wangm12/gpemu-pytorch:egpu
    # imagePullPolicy: Always
    resources:
      requests:
        ucare.cs.uchicago.edu/e-gpu: 1
        cpu: "20000m" # 20 CPUs
      limits:
        ucare.cs.uchicago.edu/e-gpu: 1
        cpu: "20000m" # 20 CPUs
    command:
    - bash
    - /app/self-check.sh
    - hi1
    - hi2
    - 20000,1,20,21
    - 90000,0,20,27
    - '1000'
    volumeMounts:
    - mountPath: /data
      name: data-volume
    # For shared memory. Otherwise will get insufficient shared memory error
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: data-volume
    hostPath:
      path: /data
      type: Directory
  - name: dshm
    emptyDir:
      medium: Memory